// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: index.proto

package friendopt

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_index_proto protoreflect.FileDescriptor

var file_index_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x66,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x6f, 0x70, 0x74, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65,
	0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0xbb, 0x01, 0x0a, 0x1d, 0x4f, 0x6e, 0x65, 0x62, 0x6f, 0x74,
	0x41, 0x70, 0x69, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4f, 0x70, 0x74, 0x47, 0x52, 0x50, 0x43,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x12, 0x1b, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x53,
	0x0a, 0x1a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x6e, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x12, 0x1b, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x49,
	0x6e, 0x74, 0x36, 0x34, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x64, 0x65, 0x7a, 0x68, 0x69, 0x73, 0x68, 0x65, 0x6e, 0x2f, 0x6f, 0x6e, 0x65, 0x62,
	0x6f, 0x74, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x6f, 0x70, 0x74, 0x3b, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x6f,
	0x70, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_index_proto_goTypes = []interface{}{
	(*wrapperspb.Int64Value)(nil), // 0: google.protobuf.Int64Value
	(*emptypb.Empty)(nil),         // 1: google.protobuf.Empty
}
var file_index_proto_depIdxs = []int32{
	0, // 0: friendopt.OnebotApiFriendOptGRPCService.DeleteFriend:input_type -> google.protobuf.Int64Value
	0, // 1: friendopt.OnebotApiFriendOptGRPCService.DeleteUnidirectionalFriend:input_type -> google.protobuf.Int64Value
	1, // 2: friendopt.OnebotApiFriendOptGRPCService.DeleteFriend:output_type -> google.protobuf.Empty
	1, // 3: friendopt.OnebotApiFriendOptGRPCService.DeleteUnidirectionalFriend:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_index_proto_init() }
func file_index_proto_init() {
	if File_index_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_index_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_index_proto_goTypes,
		DependencyIndexes: file_index_proto_depIdxs,
	}.Build()
	File_index_proto = out.File
	file_index_proto_rawDesc = nil
	file_index_proto_goTypes = nil
	file_index_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OnebotApiFriendOptGRPCServiceClient is the client API for OnebotApiFriendOptGRPCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OnebotApiFriendOptGRPCServiceClient interface {
	// 删除好友
	// delete_friend
	// user_id: int64 对方 QQ 号
	DeleteFriend(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 删除单向好友
	// delete_unidirectional_friend
	// user_id: int64 对方 QQ 号
	DeleteUnidirectionalFriend(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type onebotApiFriendOptGRPCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOnebotApiFriendOptGRPCServiceClient(cc grpc.ClientConnInterface) OnebotApiFriendOptGRPCServiceClient {
	return &onebotApiFriendOptGRPCServiceClient{cc}
}

func (c *onebotApiFriendOptGRPCServiceClient) DeleteFriend(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/friendopt.OnebotApiFriendOptGRPCService/DeleteFriend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onebotApiFriendOptGRPCServiceClient) DeleteUnidirectionalFriend(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/friendopt.OnebotApiFriendOptGRPCService/DeleteUnidirectionalFriend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OnebotApiFriendOptGRPCServiceServer is the server API for OnebotApiFriendOptGRPCService service.
type OnebotApiFriendOptGRPCServiceServer interface {
	// 删除好友
	// delete_friend
	// user_id: int64 对方 QQ 号
	DeleteFriend(context.Context, *wrapperspb.Int64Value) (*emptypb.Empty, error)
	// 删除单向好友
	// delete_unidirectional_friend
	// user_id: int64 对方 QQ 号
	DeleteUnidirectionalFriend(context.Context, *wrapperspb.Int64Value) (*emptypb.Empty, error)
}

// UnimplementedOnebotApiFriendOptGRPCServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOnebotApiFriendOptGRPCServiceServer struct {
}

func (*UnimplementedOnebotApiFriendOptGRPCServiceServer) DeleteFriend(context.Context, *wrapperspb.Int64Value) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFriend not implemented")
}
func (*UnimplementedOnebotApiFriendOptGRPCServiceServer) DeleteUnidirectionalFriend(context.Context, *wrapperspb.Int64Value) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUnidirectionalFriend not implemented")
}

func RegisterOnebotApiFriendOptGRPCServiceServer(s *grpc.Server, srv OnebotApiFriendOptGRPCServiceServer) {
	s.RegisterService(&_OnebotApiFriendOptGRPCService_serviceDesc, srv)
}

func _OnebotApiFriendOptGRPCService_DeleteFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.Int64Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnebotApiFriendOptGRPCServiceServer).DeleteFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/friendopt.OnebotApiFriendOptGRPCService/DeleteFriend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnebotApiFriendOptGRPCServiceServer).DeleteFriend(ctx, req.(*wrapperspb.Int64Value))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnebotApiFriendOptGRPCService_DeleteUnidirectionalFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.Int64Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnebotApiFriendOptGRPCServiceServer).DeleteUnidirectionalFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/friendopt.OnebotApiFriendOptGRPCService/DeleteUnidirectionalFriend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnebotApiFriendOptGRPCServiceServer).DeleteUnidirectionalFriend(ctx, req.(*wrapperspb.Int64Value))
	}
	return interceptor(ctx, in, info, handler)
}

var _OnebotApiFriendOptGRPCService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "friendopt.OnebotApiFriendOptGRPCService",
	HandlerType: (*OnebotApiFriendOptGRPCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteFriend",
			Handler:    _OnebotApiFriendOptGRPCService_DeleteFriend_Handler,
		},
		{
			MethodName: "DeleteUnidirectionalFriend",
			Handler:    _OnebotApiFriendOptGRPCService_DeleteUnidirectionalFriend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "index.proto",
}
