// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: api_friend.proto

package friend

import (
	context "context"
	model "github.com/dezhishen/onebot-sdk/pkg/model"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStrangerInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NoCache bool  `protobuf:"varint,2,opt,name=no_cache,json=noCache,proto3" json:"no_cache,omitempty"`
}

func (x *GetStrangerInfoRequest) Reset() {
	*x = GetStrangerInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_friend_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStrangerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStrangerInfoRequest) ProtoMessage() {}

func (x *GetStrangerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_friend_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStrangerInfoRequest.ProtoReflect.Descriptor instead.
func (*GetStrangerInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_friend_proto_rawDescGZIP(), []int{0}
}

func (x *GetStrangerInfoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetStrangerInfoRequest) GetNoCache() bool {
	if x != nil {
		return x.NoCache
	}
	return false
}

var File_api_friend_proto protoreflect.FileDescriptor

var file_api_friend_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x70, 0x69, 0x5f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x1a, 0x0c, 0x66, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4c, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x74, 0x72, 0x61,
	0x6e, 0x67, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x5f, 0x63,
	0x61, 0x63, 0x68, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x6e, 0x6f, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x32, 0x8e, 0x02, 0x0a, 0x1a, 0x4f, 0x6e, 0x65, 0x62, 0x6f, 0x74, 0x41, 0x70,
	0x69, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x47, 0x52, 0x50, 0x43, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x52, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x74, 0x72, 0x61, 0x6e, 0x67, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x2e, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x53, 0x74,
	0x72, 0x61, 0x6e, 0x67, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x47, 0x52, 0x50, 0x43, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x1b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x47, 0x52, 0x50, 0x43, 0x22, 0x00, 0x12, 0x54,
	0x0a, 0x1b, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x6c, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x47, 0x52,
	0x50, 0x43, 0x22, 0x00, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x7a, 0x68, 0x69, 0x73, 0x68, 0x65, 0x6e, 0x2f, 0x6f, 0x6e, 0x65,
	0x62, 0x6f, 0x74, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x3b, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_friend_proto_rawDescOnce sync.Once
	file_api_friend_proto_rawDescData = file_api_friend_proto_rawDesc
)

func file_api_friend_proto_rawDescGZIP() []byte {
	file_api_friend_proto_rawDescOnce.Do(func() {
		file_api_friend_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_friend_proto_rawDescData)
	})
	return file_api_friend_proto_rawDescData
}

var file_api_friend_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_friend_proto_goTypes = []interface{}{
	(*GetStrangerInfoRequest)(nil),       // 0: friend.GetStrangerInfoRequest
	(*emptypb.Empty)(nil),                // 1: google.protobuf.Empty
	(*model.StrangerInfoResultGRPC)(nil), // 2: model.StrangerInfoResultGRPC
	(*model.FriendListResultGRPC)(nil),   // 3: model.FriendListResultGRPC
}
var file_api_friend_proto_depIdxs = []int32{
	0, // 0: friend.OnebotApiFriendGRPCService.GetStrangerInfo:input_type -> friend.GetStrangerInfoRequest
	1, // 1: friend.OnebotApiFriendGRPCService.GetFriendList:input_type -> google.protobuf.Empty
	1, // 2: friend.OnebotApiFriendGRPCService.GetUnidirectionalFriendList:input_type -> google.protobuf.Empty
	2, // 3: friend.OnebotApiFriendGRPCService.GetStrangerInfo:output_type -> model.StrangerInfoResultGRPC
	3, // 4: friend.OnebotApiFriendGRPCService.GetFriendList:output_type -> model.FriendListResultGRPC
	3, // 5: friend.OnebotApiFriendGRPCService.GetUnidirectionalFriendList:output_type -> model.FriendListResultGRPC
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_friend_proto_init() }
func file_api_friend_proto_init() {
	if File_api_friend_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_friend_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStrangerInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_friend_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_friend_proto_goTypes,
		DependencyIndexes: file_api_friend_proto_depIdxs,
		MessageInfos:      file_api_friend_proto_msgTypes,
	}.Build()
	File_api_friend_proto = out.File
	file_api_friend_proto_rawDesc = nil
	file_api_friend_proto_goTypes = nil
	file_api_friend_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OnebotApiFriendGRPCServiceClient is the client API for OnebotApiFriendGRPCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OnebotApiFriendGRPCServiceClient interface {
	// 获取陌生人信息
	// get_stranger_info
	// user_id: 对方 QQ 号
	// no_cache: 是否不使用缓存（使用缓存可能更新不及时，但响应更快）
	GetStrangerInfo(ctx context.Context, in *GetStrangerInfoRequest, opts ...grpc.CallOption) (*model.StrangerInfoResultGRPC, error)
	// 获取好友列表
	// get_friend_list
	GetFriendList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*model.FriendListResultGRPC, error)
	// 获取单向好友列表
	// get_unidirectional_friend_list
	GetUnidirectionalFriendList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*model.FriendListResultGRPC, error)
}

type onebotApiFriendGRPCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOnebotApiFriendGRPCServiceClient(cc grpc.ClientConnInterface) OnebotApiFriendGRPCServiceClient {
	return &onebotApiFriendGRPCServiceClient{cc}
}

func (c *onebotApiFriendGRPCServiceClient) GetStrangerInfo(ctx context.Context, in *GetStrangerInfoRequest, opts ...grpc.CallOption) (*model.StrangerInfoResultGRPC, error) {
	out := new(model.StrangerInfoResultGRPC)
	err := c.cc.Invoke(ctx, "/friend.OnebotApiFriendGRPCService/GetStrangerInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onebotApiFriendGRPCServiceClient) GetFriendList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*model.FriendListResultGRPC, error) {
	out := new(model.FriendListResultGRPC)
	err := c.cc.Invoke(ctx, "/friend.OnebotApiFriendGRPCService/GetFriendList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onebotApiFriendGRPCServiceClient) GetUnidirectionalFriendList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*model.FriendListResultGRPC, error) {
	out := new(model.FriendListResultGRPC)
	err := c.cc.Invoke(ctx, "/friend.OnebotApiFriendGRPCService/GetUnidirectionalFriendList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OnebotApiFriendGRPCServiceServer is the server API for OnebotApiFriendGRPCService service.
type OnebotApiFriendGRPCServiceServer interface {
	// 获取陌生人信息
	// get_stranger_info
	// user_id: 对方 QQ 号
	// no_cache: 是否不使用缓存（使用缓存可能更新不及时，但响应更快）
	GetStrangerInfo(context.Context, *GetStrangerInfoRequest) (*model.StrangerInfoResultGRPC, error)
	// 获取好友列表
	// get_friend_list
	GetFriendList(context.Context, *emptypb.Empty) (*model.FriendListResultGRPC, error)
	// 获取单向好友列表
	// get_unidirectional_friend_list
	GetUnidirectionalFriendList(context.Context, *emptypb.Empty) (*model.FriendListResultGRPC, error)
}

// UnimplementedOnebotApiFriendGRPCServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOnebotApiFriendGRPCServiceServer struct {
}

func (*UnimplementedOnebotApiFriendGRPCServiceServer) GetStrangerInfo(context.Context, *GetStrangerInfoRequest) (*model.StrangerInfoResultGRPC, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStrangerInfo not implemented")
}
func (*UnimplementedOnebotApiFriendGRPCServiceServer) GetFriendList(context.Context, *emptypb.Empty) (*model.FriendListResultGRPC, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFriendList not implemented")
}
func (*UnimplementedOnebotApiFriendGRPCServiceServer) GetUnidirectionalFriendList(context.Context, *emptypb.Empty) (*model.FriendListResultGRPC, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnidirectionalFriendList not implemented")
}

func RegisterOnebotApiFriendGRPCServiceServer(s *grpc.Server, srv OnebotApiFriendGRPCServiceServer) {
	s.RegisterService(&_OnebotApiFriendGRPCService_serviceDesc, srv)
}

func _OnebotApiFriendGRPCService_GetStrangerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStrangerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnebotApiFriendGRPCServiceServer).GetStrangerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/friend.OnebotApiFriendGRPCService/GetStrangerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnebotApiFriendGRPCServiceServer).GetStrangerInfo(ctx, req.(*GetStrangerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnebotApiFriendGRPCService_GetFriendList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnebotApiFriendGRPCServiceServer).GetFriendList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/friend.OnebotApiFriendGRPCService/GetFriendList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnebotApiFriendGRPCServiceServer).GetFriendList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnebotApiFriendGRPCService_GetUnidirectionalFriendList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnebotApiFriendGRPCServiceServer).GetUnidirectionalFriendList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/friend.OnebotApiFriendGRPCService/GetUnidirectionalFriendList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnebotApiFriendGRPCServiceServer).GetUnidirectionalFriendList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _OnebotApiFriendGRPCService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "friend.OnebotApiFriendGRPCService",
	HandlerType: (*OnebotApiFriendGRPCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStrangerInfo",
			Handler:    _OnebotApiFriendGRPCService_GetStrangerInfo_Handler,
		},
		{
			MethodName: "GetFriendList",
			Handler:    _OnebotApiFriendGRPCService_GetFriendList_Handler,
		},
		{
			MethodName: "GetUnidirectionalFriendList",
			Handler:    _OnebotApiFriendGRPCService_GetUnidirectionalFriendList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api_friend.proto",
}
