// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: handler.proto

package message

import (
	context "context"
	model "github.com/dezhishen/onebot-sdk/pkg/model"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_handler_proto protoreflect.FileDescriptor

var file_handler_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x13, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0xc1, 0x01, 0x0a, 0x1d, 0x4f,
	0x6e, 0x65, 0x62, 0x6f, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x47, 0x52, 0x50, 0x43, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x51, 0x0a, 0x15,
	0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x47, 0x52, 0x50, 0x43, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12,
	0x4d, 0x0a, 0x13, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x47, 0x52, 0x50, 0x43, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x3b,
	0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x7a,
	0x68, 0x69, 0x73, 0x68, 0x65, 0x6e, 0x2f, 0x6f, 0x6e, 0x65, 0x62, 0x6f, 0x74, 0x2d, 0x73, 0x64,
	0x6b, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x3b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var file_handler_proto_goTypes = []interface{}{
	(*model.EventMessagePrivateGRPC)(nil), // 0: model.EventMessagePrivateGRPC
	(*model.EventMessageGroupGRPC)(nil),   // 1: model.EventMessageGroupGRPC
	(*emptypb.Empty)(nil),                 // 2: google.protobuf.Empty
}
var file_handler_proto_depIdxs = []int32{
	0, // 0: message.OnebotEventMessageGRPCService.HandlerPrivateMessage:input_type -> model.EventMessagePrivateGRPC
	1, // 1: message.OnebotEventMessageGRPCService.HandlerGroupMessage:input_type -> model.EventMessageGroupGRPC
	2, // 2: message.OnebotEventMessageGRPCService.HandlerPrivateMessage:output_type -> google.protobuf.Empty
	2, // 3: message.OnebotEventMessageGRPCService.HandlerGroupMessage:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_handler_proto_init() }
func file_handler_proto_init() {
	if File_handler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_handler_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_handler_proto_goTypes,
		DependencyIndexes: file_handler_proto_depIdxs,
	}.Build()
	File_handler_proto = out.File
	file_handler_proto_rawDesc = nil
	file_handler_proto_goTypes = nil
	file_handler_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OnebotEventMessageGRPCServiceClient is the client API for OnebotEventMessageGRPCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OnebotEventMessageGRPCServiceClient interface {
	// ListenMessagePrivate(handler func(data model.EventMessagePrivate) error)
	HandlerPrivateMessage(ctx context.Context, in *model.EventMessagePrivateGRPC, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListenMessageGroup(handler func(data model.EventMessageGroup) error)
	HandlerGroupMessage(ctx context.Context, in *model.EventMessageGroupGRPC, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type onebotEventMessageGRPCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOnebotEventMessageGRPCServiceClient(cc grpc.ClientConnInterface) OnebotEventMessageGRPCServiceClient {
	return &onebotEventMessageGRPCServiceClient{cc}
}

func (c *onebotEventMessageGRPCServiceClient) HandlerPrivateMessage(ctx context.Context, in *model.EventMessagePrivateGRPC, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/message.OnebotEventMessageGRPCService/HandlerPrivateMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onebotEventMessageGRPCServiceClient) HandlerGroupMessage(ctx context.Context, in *model.EventMessageGroupGRPC, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/message.OnebotEventMessageGRPCService/HandlerGroupMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OnebotEventMessageGRPCServiceServer is the server API for OnebotEventMessageGRPCService service.
type OnebotEventMessageGRPCServiceServer interface {
	// ListenMessagePrivate(handler func(data model.EventMessagePrivate) error)
	HandlerPrivateMessage(context.Context, *model.EventMessagePrivateGRPC) (*emptypb.Empty, error)
	// ListenMessageGroup(handler func(data model.EventMessageGroup) error)
	HandlerGroupMessage(context.Context, *model.EventMessageGroupGRPC) (*emptypb.Empty, error)
}

// UnimplementedOnebotEventMessageGRPCServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOnebotEventMessageGRPCServiceServer struct {
}

func (*UnimplementedOnebotEventMessageGRPCServiceServer) HandlerPrivateMessage(context.Context, *model.EventMessagePrivateGRPC) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandlerPrivateMessage not implemented")
}
func (*UnimplementedOnebotEventMessageGRPCServiceServer) HandlerGroupMessage(context.Context, *model.EventMessageGroupGRPC) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandlerGroupMessage not implemented")
}

func RegisterOnebotEventMessageGRPCServiceServer(s *grpc.Server, srv OnebotEventMessageGRPCServiceServer) {
	s.RegisterService(&_OnebotEventMessageGRPCService_serviceDesc, srv)
}

func _OnebotEventMessageGRPCService_HandlerPrivateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(model.EventMessagePrivateGRPC)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnebotEventMessageGRPCServiceServer).HandlerPrivateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.OnebotEventMessageGRPCService/HandlerPrivateMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnebotEventMessageGRPCServiceServer).HandlerPrivateMessage(ctx, req.(*model.EventMessagePrivateGRPC))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnebotEventMessageGRPCService_HandlerGroupMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(model.EventMessageGroupGRPC)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnebotEventMessageGRPCServiceServer).HandlerGroupMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.OnebotEventMessageGRPCService/HandlerGroupMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnebotEventMessageGRPCServiceServer).HandlerGroupMessage(ctx, req.(*model.EventMessageGroupGRPC))
	}
	return interceptor(ctx, in, info, handler)
}

var _OnebotEventMessageGRPCService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "message.OnebotEventMessageGRPCService",
	HandlerType: (*OnebotEventMessageGRPCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandlerPrivateMessage",
			Handler:    _OnebotEventMessageGRPCService_HandlerPrivateMessage_Handler,
		},
		{
			MethodName: "HandlerGroupMessage",
			Handler:    _OnebotEventMessageGRPCService_HandlerGroupMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "handler.proto",
}
