// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: event_request.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventRequestBaseGRPC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventBase *EventBaseGRPC `protobuf:"bytes,1,opt,name=eventBase,proto3" json:"eventBase,omitempty"`
	//请求类型
	RequestType string `protobuf:"bytes,2,opt,name=request_type,json=requestType,proto3" json:"request_type,omitempty"`
}

func (x *EventRequestBaseGRPC) Reset() {
	*x = EventRequestBaseGRPC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventRequestBaseGRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRequestBaseGRPC) ProtoMessage() {}

func (x *EventRequestBaseGRPC) ProtoReflect() protoreflect.Message {
	mi := &file_event_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRequestBaseGRPC.ProtoReflect.Descriptor instead.
func (*EventRequestBaseGRPC) Descriptor() ([]byte, []int) {
	return file_event_request_proto_rawDescGZIP(), []int{0}
}

func (x *EventRequestBaseGRPC) GetEventBase() *EventBaseGRPC {
	if x != nil {
		return x.EventBase
	}
	return nil
}

func (x *EventRequestBaseGRPC) GetRequestType() string {
	if x != nil {
		return x.RequestType
	}
	return ""
}

type EventRequestFriendGRPC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventRequestBase *EventRequestBaseGRPC `protobuf:"bytes,1,opt,name=eventRequestBase,proto3" json:"eventRequestBase,omitempty"`
	//发送请求的QQ
	UserId int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	//验证信息
	Comment string `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	//请求 flag，在调用处理请求的 API 时需要传入
	Flag string `protobuf:"bytes,4,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *EventRequestFriendGRPC) Reset() {
	*x = EventRequestFriendGRPC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_request_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventRequestFriendGRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRequestFriendGRPC) ProtoMessage() {}

func (x *EventRequestFriendGRPC) ProtoReflect() protoreflect.Message {
	mi := &file_event_request_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRequestFriendGRPC.ProtoReflect.Descriptor instead.
func (*EventRequestFriendGRPC) Descriptor() ([]byte, []int) {
	return file_event_request_proto_rawDescGZIP(), []int{1}
}

func (x *EventRequestFriendGRPC) GetEventRequestBase() *EventRequestBaseGRPC {
	if x != nil {
		return x.EventRequestBase
	}
	return nil
}

func (x *EventRequestFriendGRPC) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *EventRequestFriendGRPC) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *EventRequestFriendGRPC) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

type EventRequestGroupGRPC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventRequestBase *EventRequestBaseGRPC `protobuf:"bytes,1,opt,name=eventRequestBase,proto3" json:"eventRequestBase,omitempty"`
	//add、invite	请求子类型，分别表示加群请求、邀请登录号入群
	SubType string `protobuf:"bytes,2,opt,name=sub_type,json=subType,proto3" json:"sub_type,omitempty"`
	//群号
	GroupId int64 `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	//发送请求的QQ
	UserId int64 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	//验证信息
	Comment string `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	//请求 flag，在调用处理请求的 API 时需要传入
	Flag string `protobuf:"bytes,6,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *EventRequestGroupGRPC) Reset() {
	*x = EventRequestGroupGRPC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_request_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventRequestGroupGRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRequestGroupGRPC) ProtoMessage() {}

func (x *EventRequestGroupGRPC) ProtoReflect() protoreflect.Message {
	mi := &file_event_request_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRequestGroupGRPC.ProtoReflect.Descriptor instead.
func (*EventRequestGroupGRPC) Descriptor() ([]byte, []int) {
	return file_event_request_proto_rawDescGZIP(), []int{2}
}

func (x *EventRequestGroupGRPC) GetEventRequestBase() *EventRequestBaseGRPC {
	if x != nil {
		return x.EventRequestBase
	}
	return nil
}

func (x *EventRequestGroupGRPC) GetSubType() string {
	if x != nil {
		return x.SubType
	}
	return ""
}

func (x *EventRequestGroupGRPC) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *EventRequestGroupGRPC) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *EventRequestGroupGRPC) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *EventRequestGroupGRPC) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

var File_event_request_proto protoreflect.FileDescriptor

var file_event_request_proto_rawDesc = []byte{
	0x0a, 0x13, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x1a, 0x0b, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6d, 0x0a, 0x14, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x61, 0x73, 0x65, 0x47, 0x52, 0x50,
	0x43, 0x12, 0x32, 0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x61, 0x73, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x42, 0x61, 0x73, 0x65, 0x47, 0x52, 0x50, 0x43, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x42, 0x61, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0xa8, 0x01, 0x0a, 0x16, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x47,
	0x52, 0x50, 0x43, 0x12, 0x47, 0x0a, 0x10, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x42, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x42, 0x61, 0x73, 0x65, 0x47, 0x52, 0x50, 0x43, 0x52, 0x10, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x61, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66,
	0x6c, 0x61, 0x67, 0x22, 0xdd, 0x01, 0x0a, 0x15, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x47, 0x52, 0x50, 0x43, 0x12, 0x47, 0x0a,
	0x10, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x61, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x61, 0x73, 0x65,
	0x47, 0x52, 0x50, 0x43, 0x52, 0x10, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x42, 0x61, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x75, 0x62, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66,
	0x6c, 0x61, 0x67, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2e, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_event_request_proto_rawDescOnce sync.Once
	file_event_request_proto_rawDescData = file_event_request_proto_rawDesc
)

func file_event_request_proto_rawDescGZIP() []byte {
	file_event_request_proto_rawDescOnce.Do(func() {
		file_event_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_event_request_proto_rawDescData)
	})
	return file_event_request_proto_rawDescData
}

var file_event_request_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_event_request_proto_goTypes = []interface{}{
	(*EventRequestBaseGRPC)(nil),   // 0: model.EventRequestBaseGRPC
	(*EventRequestFriendGRPC)(nil), // 1: model.EventRequestFriendGRPC
	(*EventRequestGroupGRPC)(nil),  // 2: model.EventRequestGroupGRPC
	(*EventBaseGRPC)(nil),          // 3: model.EventBaseGRPC
}
var file_event_request_proto_depIdxs = []int32{
	3, // 0: model.EventRequestBaseGRPC.eventBase:type_name -> model.EventBaseGRPC
	0, // 1: model.EventRequestFriendGRPC.eventRequestBase:type_name -> model.EventRequestBaseGRPC
	0, // 2: model.EventRequestGroupGRPC.eventRequestBase:type_name -> model.EventRequestBaseGRPC
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_event_request_proto_init() }
func file_event_request_proto_init() {
	if File_event_request_proto != nil {
		return
	}
	file_event_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_event_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventRequestBaseGRPC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_request_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventRequestFriendGRPC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_request_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventRequestGroupGRPC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_event_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_request_proto_goTypes,
		DependencyIndexes: file_event_request_proto_depIdxs,
		MessageInfos:      file_event_request_proto_msgTypes,
	}.Build()
	File_event_request_proto = out.File
	file_event_request_proto_rawDesc = nil
	file_event_request_proto_goTypes = nil
	file_event_request_proto_depIdxs = nil
}
