// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: friend.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StrangerInfoGRPC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 	UserId int64 `json:"user_id"`
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 	Nickname string `json:"nickname"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// 	Sex string `json:"sex"`
	Sex string `protobuf:"bytes,3,opt,name=sex,proto3" json:"sex,omitempty"`
	// 	Age int32 `json:"age"`
	Age int32 `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	// 	Qid string `json:"qid"`
	Qid string `protobuf:"bytes,5,opt,name=qid,proto3" json:"qid,omitempty"`
	// 	Level int32 `json:"level"`
	Level int32 `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	// 	LoginDays int32 `json:"login_days"`
	LoginDays int32 `protobuf:"varint,7,opt,name=login_days,json=loginDays,proto3" json:"login_days,omitempty"`
}

func (x *StrangerInfoGRPC) Reset() {
	*x = StrangerInfoGRPC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrangerInfoGRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrangerInfoGRPC) ProtoMessage() {}

func (x *StrangerInfoGRPC) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrangerInfoGRPC.ProtoReflect.Descriptor instead.
func (*StrangerInfoGRPC) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{0}
}

func (x *StrangerInfoGRPC) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *StrangerInfoGRPC) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *StrangerInfoGRPC) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *StrangerInfoGRPC) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *StrangerInfoGRPC) GetQid() string {
	if x != nil {
		return x.Qid
	}
	return ""
}

func (x *StrangerInfoGRPC) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *StrangerInfoGRPC) GetLoginDays() int32 {
	if x != nil {
		return x.LoginDays
	}
	return 0
}

type StrangerInfoResultGRPC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 	Data    *StrangerInfo `json:"data"`
	Data *StrangerInfoGRPC `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// 	Retcode int64         `json:"retcode"`
	Retcode int64 `protobuf:"varint,2,opt,name=retcode,proto3" json:"retcode,omitempty"`
	// 	Status  string        `json:"status"`
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// 	Msg     string        `json:"msg"`
	Msg string `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	// 	Wording string        `json:"wording"`
	Wording string `protobuf:"bytes,5,opt,name=wording,proto3" json:"wording,omitempty"`
}

func (x *StrangerInfoResultGRPC) Reset() {
	*x = StrangerInfoResultGRPC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrangerInfoResultGRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrangerInfoResultGRPC) ProtoMessage() {}

func (x *StrangerInfoResultGRPC) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrangerInfoResultGRPC.ProtoReflect.Descriptor instead.
func (*StrangerInfoResultGRPC) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{1}
}

func (x *StrangerInfoResultGRPC) GetData() *StrangerInfoGRPC {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StrangerInfoResultGRPC) GetRetcode() int64 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *StrangerInfoResultGRPC) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StrangerInfoResultGRPC) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *StrangerInfoResultGRPC) GetWording() string {
	if x != nil {
		return x.Wording
	}
	return ""
}

type FriendGRPC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 	UserId int64 `json:"user_id"`
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 	Nickname string `json:"nickname"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// 	Remark string `json:"remark"`
	Remark string `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
}

func (x *FriendGRPC) Reset() {
	*x = FriendGRPC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendGRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendGRPC) ProtoMessage() {}

func (x *FriendGRPC) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendGRPC.ProtoReflect.Descriptor instead.
func (*FriendGRPC) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{2}
}

func (x *FriendGRPC) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FriendGRPC) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *FriendGRPC) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type FriendListResultGRPC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 	Data    []*Friend `json:"data"`
	Data []*FriendGRPC `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	// 	Retcode int64     `json:"retcode"`
	Retcode int64 `protobuf:"varint,2,opt,name=retcode,proto3" json:"retcode,omitempty"`
	// 	Status  string    `json:"status"`
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// 	Msg     string    `json:"msg"`
	Msg string `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	// 	Wording string    `json:"wording"`
	Wording string `protobuf:"bytes,5,opt,name=wording,proto3" json:"wording,omitempty"`
}

func (x *FriendListResultGRPC) Reset() {
	*x = FriendListResultGRPC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_friend_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendListResultGRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendListResultGRPC) ProtoMessage() {}

func (x *FriendListResultGRPC) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendListResultGRPC.ProtoReflect.Descriptor instead.
func (*FriendListResultGRPC) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{3}
}

func (x *FriendListResultGRPC) GetData() []*FriendGRPC {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FriendListResultGRPC) GetRetcode() int64 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *FriendListResultGRPC) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FriendListResultGRPC) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *FriendListResultGRPC) GetWording() string {
	if x != nil {
		return x.Wording
	}
	return ""
}

var File_friend_proto protoreflect.FileDescriptor

var file_friend_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0xb2, 0x01, 0x0a, 0x10, 0x53, 0x74, 0x72, 0x61, 0x6e, 0x67,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x52, 0x50, 0x43, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x65,
	0x78, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x71, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x71, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x64, 0x61, 0x79, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x44, 0x61, 0x79, 0x73, 0x22, 0xa3, 0x01, 0x0a, 0x16, 0x53,
	0x74, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x47, 0x52, 0x50, 0x43, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x53, 0x74, 0x72, 0x61,
	0x6e, 0x67, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x52, 0x50, 0x43, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x6f, 0x72, 0x64, 0x69, 0x6e,
	0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67,
	0x22, 0x59, 0x0a, 0x0a, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x47, 0x52, 0x50, 0x43, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0x9b, 0x01, 0x0a, 0x14,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x47, 0x52, 0x50, 0x43, 0x12, 0x25, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x47, 0x52, 0x50, 0x43, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x72,
	0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x65,
	0x74, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12,
	0x18, 0x0a, 0x07, 0x77, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x77, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2e, 0x2f,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_friend_proto_rawDescOnce sync.Once
	file_friend_proto_rawDescData = file_friend_proto_rawDesc
)

func file_friend_proto_rawDescGZIP() []byte {
	file_friend_proto_rawDescOnce.Do(func() {
		file_friend_proto_rawDescData = protoimpl.X.CompressGZIP(file_friend_proto_rawDescData)
	})
	return file_friend_proto_rawDescData
}

var file_friend_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_friend_proto_goTypes = []interface{}{
	(*StrangerInfoGRPC)(nil),       // 0: model.StrangerInfoGRPC
	(*StrangerInfoResultGRPC)(nil), // 1: model.StrangerInfoResultGRPC
	(*FriendGRPC)(nil),             // 2: model.FriendGRPC
	(*FriendListResultGRPC)(nil),   // 3: model.FriendListResultGRPC
}
var file_friend_proto_depIdxs = []int32{
	0, // 0: model.StrangerInfoResultGRPC.data:type_name -> model.StrangerInfoGRPC
	2, // 1: model.FriendListResultGRPC.data:type_name -> model.FriendGRPC
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_friend_proto_init() }
func file_friend_proto_init() {
	if File_friend_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_friend_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StrangerInfoGRPC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StrangerInfoResultGRPC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendGRPC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_friend_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendListResultGRPC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_friend_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_friend_proto_goTypes,
		DependencyIndexes: file_friend_proto_depIdxs,
		MessageInfos:      file_friend_proto_msgTypes,
	}.Build()
	File_friend_proto = out.File
	file_friend_proto_rawDesc = nil
	file_friend_proto_goTypes = nil
	file_friend_proto_depIdxs = nil
}
