// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: message_element_gift.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageElementGiftGRPC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// qq	int64	接收礼物的成员
	Qq int64 `protobuf:"varint,1,opt,name=Qq,proto3" json:"Qq,omitempty"`
	// id	int	礼物的类型
	// 0	甜 Wink
	// 1	快乐肥宅水
	// 2	幸运手链
	// 3	卡布奇诺
	// 4	猫咪手表
	// 5	绒绒手套
	// 6	彩虹糖果
	// 7	坚强
	// 8	告白话筒
	// 9	牵你的手
	// 10	可爱猫咪
	// 11	神秘面具
	// 12	我超忙的
	// 13	爱心口罩
	Id int64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MessageElementGiftGRPC) Reset() {
	*x = MessageElementGiftGRPC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_element_gift_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageElementGiftGRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageElementGiftGRPC) ProtoMessage() {}

func (x *MessageElementGiftGRPC) ProtoReflect() protoreflect.Message {
	mi := &file_message_element_gift_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageElementGiftGRPC.ProtoReflect.Descriptor instead.
func (*MessageElementGiftGRPC) Descriptor() ([]byte, []int) {
	return file_message_element_gift_proto_rawDescGZIP(), []int{0}
}

func (x *MessageElementGiftGRPC) GetQq() int64 {
	if x != nil {
		return x.Qq
	}
	return 0
}

func (x *MessageElementGiftGRPC) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_message_element_gift_proto protoreflect.FileDescriptor

var file_message_element_gift_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x67, 0x69, 0x66, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x22, 0x38, 0x0a, 0x16, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x47, 0x69, 0x66, 0x74, 0x47, 0x52, 0x50, 0x43, 0x12, 0x0e, 0x0a,
	0x02, 0x51, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x51, 0x71, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x42, 0x31, 0x5a,
	0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x7a, 0x68,
	0x69, 0x73, 0x68, 0x65, 0x6e, 0x2f, 0x6f, 0x6e, 0x65, 0x62, 0x6f, 0x74, 0x2d, 0x73, 0x64, 0x6b,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x3b, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_element_gift_proto_rawDescOnce sync.Once
	file_message_element_gift_proto_rawDescData = file_message_element_gift_proto_rawDesc
)

func file_message_element_gift_proto_rawDescGZIP() []byte {
	file_message_element_gift_proto_rawDescOnce.Do(func() {
		file_message_element_gift_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_element_gift_proto_rawDescData)
	})
	return file_message_element_gift_proto_rawDescData
}

var file_message_element_gift_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_element_gift_proto_goTypes = []interface{}{
	(*MessageElementGiftGRPC)(nil), // 0: model.MessageElementGiftGRPC
}
var file_message_element_gift_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_element_gift_proto_init() }
func file_message_element_gift_proto_init() {
	if File_message_element_gift_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_element_gift_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageElementGiftGRPC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_element_gift_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_element_gift_proto_goTypes,
		DependencyIndexes: file_message_element_gift_proto_depIdxs,
		MessageInfos:      file_message_element_gift_proto_msgTypes,
	}.Build()
	File_message_element_gift_proto = out.File
	file_message_element_gift_proto_rawDesc = nil
	file_message_element_gift_proto_goTypes = nil
	file_message_element_gift_proto_depIdxs = nil
}
